name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull with compose
        run: docker-compose pull
      -
        name: create .env file
        run: |
          touch .env
          echo REDIS_USER="${{secrets.REDIS_USER }}" >> .env
          echo REDIS_PASSWORD="${{secrets.REDIS_PASSWORD }}" >> .env
          echo REDIS_ADDRESS="${{secrets.REDIS_ADDRESS}}" >> .env
          echo REDIS_PORT="${{secrets.REDIS_PORT }}" >> .env
      -
        name: Run tests
        run: docker-compose up --abort-on-container-exit
